name = "birl"
version = "1.1.0"

description = "Date / Time handling for Gleam"
licences = ["Apache-2.0"]
links = [{title = "Gleam", href = "https://gleam.run"}]
repository = {type = "github", user = "massivefermion", repo = "birl"}

gleam = ">= 0.32.0"
internal_modules = [
  "birl/zones",
]

[dependencies]
gleam_stdlib = "~> 0.32"
ranger = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
