name = "birl"
version = "0.6.1"

description = "datetime handling for gleam"
licences = ["Apache-2.0"]
links = [{title = "gleam", href = "https://gleam.run"}]
repository = {type = "github", user = "massivefermion", repo = "birl"}

[dependencies]
gleam_stdlib = "~> 0.27"

[dev-dependencies]
gleeunit = "~> 0.10"
