name = "birl"
version = "1.4.0"

description = "Date / Time handling for Gleam"
gleam = ">= 0.32.0"
internal_modules = ["birl/zones"]
licences = ["Apache-2.0"]
repository = { type = "github", user = "massivefermion", repo = "birl" }
links = [{ title = "Gleam", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.34"
ranger = "~> 1.1"

[dev-dependencies]
gleeunit = "~> 1.0"
