name = "birl"
version = "0.4.0"

description = "datetime handling for gleam"
licences = ["Apache-2.0"]
links = [{ title = "gleam", href = "https://gleam.run" }]
repository = { type = "github", user = "massivefermion", repo = "birl" }

[dependencies]
gleam_stdlib = "~> 0.26"

[dev-dependencies]
gleeunit = "~> 0.10"
